apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-app
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: collections
  source:
    path: .
    plugin:
      env:
      - name: KONFIGURE_APP_NAME
        value: cert-manager-app
      - name: KONFIGURE_APP_VERSION
        value: 2.8.0
      - name: KONFIGURE_APP_CATALOG
        value: control-plane-catalog
      name: konfigure
    repoURL: https://github.com/giantswarm/config.git
    targetRevision: v1
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
