apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: net-exporter
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: collections
  source:
    path: .
    plugin:
      env:
      - name: KONFIGURE_APP_NAME
        value: net-exporter
      - name: KONFIGURE_APP_VERSION
        value: 1.10.2
      - name: KONFIGURE_APP_CATALOG
        value: control-plane-catalog
      name: konfigure
    repoURL: https://github.com/giantswarm/config.git
    targetRevision: FIXME
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
