apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: vertical-pod-autoscaler-crd
  namespace: argocd
spec:
  destination:
    namespace: giantswarm
    server: https://kubernetes.default.svc
  project: collections
  source:
    path: .
    plugin:
      env:
      - name: KONFIGURE_APP_NAME
        value: vertical-pod-autoscaler-crd
      - name: KONFIGURE_APP_VERSION
        value: 1.0.0
      - name: KONFIGURE_APP_CATALOG
        value: control-plane-catalog
      name: konfigure
    repoURL: https://github.com/giantswarm/config.git
    targetRevision: v1
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
